spring:
  application:
    name: backend

  config:
    import: file:./.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  artemis:
    mode: native
    broker-url: ${ARTEMIS_URL}
    user: admin
    password: admin



library:
  max-borrowing-days: 30
  artemis:
    reminder-queue-name: "reminder-queue"
    return-queue-name: "return-queue"