spring:
  application:
    name: backend

  config:
    import: file:./.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  artemis:
    mode: native
    broker-url: ${ARTEMIS_URL}
    user: ${ARTEMIS_USER}
    password: ${ARTEMIS_PASSWORD}

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true



library:
  max-borrowing-days: 30
  templates:
    return: "email_templates/return_template.json"
  artemis:
    reminder-queue-name: "reminder-queue"
    return-queue-name: "return-queue"